In [1]:
import numpy as np
import pandas as pd

# Binary Classification with a Bank Churn Dataset

train = pd.read_csv(
    r"C:\Users\IVAN\Desktop\Machine-Learning-Roadmap-Theory-and-Practice\Files\Binary Classification with a Bank Churn Dataset\train.csv",
    sep=','
)

X_test = pd.read_csv(
    r"C:\Users\IVAN\Desktop\Machine-Learning-Roadmap-Theory-and-Practice\Files\Binary Classification with a Bank Churn Dataset\test.csv",
    sep=','
)

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# X_train.info()
# X_train.describe()

X_train = train.drop(columns=['Exited'])
y_train = train['Exited']

X_train = X_train.drop(columns=['id', 'CustomerId', 'Surname'])
X_test = X_test.drop(columns=['id', 'CustomerId', 'Surname'])

print(X_train['Geography'].unique())
print(X_train['Gender'].unique())
print(X_train.shape)

X_tr, X_te, y_tr, y_te = train_test_split(X_train, y_train, test_size=0.2, random_state=42, stratify=y_train)

cat_features = ['Geography', 'Gender']

# for i in cat_features:
#     print(X_tr[i].dtype)
# X_train.head()

<StringArray>
['France', 'Spain', 'Germany']
Length: 3, dtype: str
<StringArray>
['Male', 'Female']
Length: 2, dtype: str
(165034, 10)

In [3]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import roc_auc_score
from catboost import CatBoostClassifier


model = CatBoostClassifier(
    iterations=500,
    cat_features=cat_features,
    random_state=42
)

model.fit(X_tr, y_tr)

print('Train acc:', accuracy_score(model.predict(X_tr), y_tr))
print('Val acc:', accuracy_score(model.predict(X_te), y_te))

y_pred_proba = model.predict_proba(X_te)[:, 1]
roc_auc = roc_auc_score(y_te, y_pred_proba)
print(f"ROC-AUC Score: {roc_auc:.4f}")

Learning rate set to 0.156495
0:	learn: 0.5665335	total: 217ms	remaining: 1m 48s
1:	learn: 0.4875305	total: 274ms	remaining: 1m 8s
2:	learn: 0.4338593	total: 332ms	remaining: 55s
3:	learn: 0.4003569	total: 387ms	remaining: 48s
4:	learn: 0.3768449	total: 447ms	remaining: 44.3s
5:	learn: 0.3616209	total: 512ms	remaining: 42.2s
6:	learn: 0.3511948	total: 577ms	remaining: 40.6s
7:	learn: 0.3440154	total: 640ms	remaining: 39.4s
8:	learn: 0.3389373	total: 701ms	remaining: 38.3s
9:	learn: 0.3356159	total: 762ms	remaining: 37.3s
10:	learn: 0.3324036	total: 824ms	remaining: 36.6s
11:	learn: 0.3298442	total: 888ms	remaining: 36.1s
12:	learn: 0.3280948	total: 953ms	remaining: 35.7s
13:	learn: 0.3269245	total: 1.01s	remaining: 35.2s
14:	learn: 0.3259745	total: 1.08s	remaining: 35s
15:	learn: 0.3251354	total: 1.14s	remaining: 34.6s
16:	learn: 0.3243785	total: 1.21s	remaining: 34.3s
17:	learn: 0.3238969	total: 1.27s	remaining: 34.1s
18:	learn: 0.3233900	total: 1.33s	remaining: 33.8s
19:	learn: 0.3229886	total: 1.4s	remaining: 33.6s
20:	learn: 0.3225995	total: 1.47s	remaining: 33.5s
21:	learn: 0.3222719	total: 1.53s	remaining: 33.3s
22:	learn: 0.3218651	total: 1.6s	remaining: 33.2s
23:	learn: 0.3216437	total: 1.67s	remaining: 33.1s
24:	learn: 0.3213459	total: 1.73s	remaining: 32.9s
25:	learn: 0.3211285	total: 1.8s	remaining: 32.8s
26:	learn: 0.3208903	total: 1.87s	remaining: 32.8s
27:	learn: 0.3207082	total: 1.94s	remaining: 32.6s
28:	learn: 0.3205145	total: 2s	remaining: 32.5s
29:	learn: 0.3203278	total: 2.06s	remaining: 32.4s
30:	learn: 0.3201862	total: 2.13s	remaining: 32.2s
31:	learn: 0.3199960	total: 2.19s	remaining: 32.1s
32:	learn: 0.3198213	total: 2.26s	remaining: 32s
33:	learn: 0.3196802	total: 2.32s	remaining: 31.8s
34:	learn: 0.3195490	total: 2.38s	remaining: 31.7s
35:	learn: 0.3194090	total: 2.44s	remaining: 31.5s
36:	learn: 0.3192636	total: 2.51s	remaining: 31.4s
37:	learn: 0.3191796	total: 2.57s	remaining: 31.3s
38:	learn: 0.3191209	total: 2.63s	remaining: 31.1s
39:	learn: 0.3190296	total: 2.69s	remaining: 31s
40:	learn: 0.3189647	total: 2.75s	remaining: 30.8s
41:	learn: 0.3188857	total: 2.82s	remaining: 30.7s
42:	learn: 0.3187303	total: 2.88s	remaining: 30.6s
43:	learn: 0.3185848	total: 2.96s	remaining: 30.6s
44:	learn: 0.3184601	total: 3.03s	remaining: 30.6s
45:	learn: 0.3183475	total: 3.09s	remaining: 30.5s
46:	learn: 0.3182338	total: 3.18s	remaining: 30.7s
47:	learn: 0.3181676	total: 3.25s	remaining: 30.7s
48:	learn: 0.3180737	total: 3.33s	remaining: 30.6s
49:	learn: 0.3179736	total: 3.4s	remaining: 30.6s
50:	learn: 0.3178702	total: 3.47s	remaining: 30.5s
51:	learn: 0.3177922	total: 3.54s	remaining: 30.5s
52:	learn: 0.3177666	total: 3.59s	remaining: 30.3s
53:	learn: 0.3177088	total: 3.67s	remaining: 30.3s
54:	learn: 0.3176577	total: 3.73s	remaining: 30.2s
55:	learn: 0.3175821	total: 3.79s	remaining: 30.1s
56:	learn: 0.3174910	total: 3.86s	remaining: 30s
57:	learn: 0.3174002	total: 3.92s	remaining: 29.9s
58:	learn: 0.3173120	total: 3.99s	remaining: 29.9s
59:	learn: 0.3172577	total: 4.06s	remaining: 29.8s
60:	learn: 0.3171948	total: 4.13s	remaining: 29.7s
61:	learn: 0.3171344	total: 4.2s	remaining: 29.7s
62:	learn: 0.3170465	total: 4.27s	remaining: 29.6s
63:	learn: 0.3169850	total: 4.33s	remaining: 29.5s
64:	learn: 0.3169057	total: 4.39s	remaining: 29.4s
65:	learn: 0.3168256	total: 4.46s	remaining: 29.3s
66:	learn: 0.3167873	total: 4.53s	remaining: 29.3s
67:	learn: 0.3167293	total: 4.59s	remaining: 29.2s
68:	learn: 0.3166095	total: 4.66s	remaining: 29.1s
69:	learn: 0.3165494	total: 4.72s	remaining: 29s
70:	learn: 0.3165490	total: 4.77s	remaining: 28.8s
71:	learn: 0.3164763	total: 4.83s	remaining: 28.7s
72:	learn: 0.3164036	total: 4.9s	remaining: 28.6s
73:	learn: 0.3163422	total: 4.96s	remaining: 28.6s
74:	learn: 0.3162530	total: 5.03s	remaining: 28.5s
75:	learn: 0.3161924	total: 5.1s	remaining: 28.4s
76:	learn: 0.3161029	total: 5.17s	remaining: 28.4s
77:	learn: 0.3160101	total: 5.24s	remaining: 28.4s
78:	learn: 0.3159569	total: 5.3s	remaining: 28.3s
79:	learn: 0.3158933	total: 5.37s	remaining: 28.2s
80:	learn: 0.3158262	total: 5.44s	remaining: 28.1s
81:	learn: 0.3157719	total: 5.5s	remaining: 28.1s
82:	learn: 0.3156836	total: 5.57s	remaining: 28s
83:	learn: 0.3155901	total: 5.64s	remaining: 27.9s
84:	learn: 0.3155154	total: 5.71s	remaining: 27.9s
85:	learn: 0.3154458	total: 5.78s	remaining: 27.8s
86:	learn: 0.3153596	total: 5.84s	remaining: 27.7s
87:	learn: 0.3152985	total: 5.91s	remaining: 27.7s
88:	learn: 0.3152226	total: 5.97s	remaining: 27.6s
89:	learn: 0.3151425	total: 6.04s	remaining: 27.5s
90:	learn: 0.3150552	total: 6.1s	remaining: 27.4s
91:	learn: 0.3149664	total: 6.17s	remaining: 27.3s
92:	learn: 0.3148957	total: 6.23s	remaining: 27.3s
93:	learn: 0.3148261	total: 6.35s	remaining: 27.4s
94:	learn: 0.3147472	total: 6.44s	remaining: 27.5s
95:	learn: 0.3146863	total: 6.51s	remaining: 27.4s
96:	learn: 0.3146219	total: 6.59s	remaining: 27.4s
97:	learn: 0.3145512	total: 6.69s	remaining: 27.5s
98:	learn: 0.3144801	total: 6.76s	remaining: 27.4s
99:	learn: 0.3143885	total: 6.88s	remaining: 27.5s
100:	learn: 0.3143231	total: 6.94s	remaining: 27.4s
101:	learn: 0.3142398	total: 7.01s	remaining: 27.3s
102:	learn: 0.3141473	total: 7.07s	remaining: 27.3s
103:	learn: 0.3141027	total: 7.14s	remaining: 27.2s
104:	learn: 0.3140280	total: 7.21s	remaining: 27.1s
105:	learn: 0.3139439	total: 7.28s	remaining: 27.1s
106:	learn: 0.3138679	total: 7.36s	remaining: 27s
107:	learn: 0.3137811	total: 7.43s	remaining: 27s
108:	learn: 0.3136901	total: 7.5s	remaining: 26.9s
109:	learn: 0.3136482	total: 7.56s	remaining: 26.8s
110:	learn: 0.3136002	total: 7.63s	remaining: 26.7s
111:	learn: 0.3135551	total: 7.69s	remaining: 26.6s
112:	learn: 0.3135135	total: 7.75s	remaining: 26.5s
113:	learn: 0.3134544	total: 7.81s	remaining: 26.5s
114:	learn: 0.3134069	total: 7.88s	remaining: 26.4s
115:	learn: 0.3133317	total: 7.95s	remaining: 26.3s
116:	learn: 0.3132506	total: 8.01s	remaining: 26.2s
117:	learn: 0.3131658	total: 8.08s	remaining: 26.2s
118:	learn: 0.3131055	total: 8.15s	remaining: 26.1s
119:	learn: 0.3130537	total: 8.22s	remaining: 26s
120:	learn: 0.3129985	total: 8.28s	remaining: 25.9s
121:	learn: 0.3129227	total: 8.35s	remaining: 25.9s
122:	learn: 0.3128658	total: 8.43s	remaining: 25.8s
123:	learn: 0.3127942	total: 8.49s	remaining: 25.8s
124:	learn: 0.3127518	total: 8.56s	remaining: 25.7s
125:	learn: 0.3126910	total: 8.63s	remaining: 25.6s
126:	learn: 0.3126061	total: 8.7s	remaining: 25.5s
127:	learn: 0.3125423	total: 8.76s	remaining: 25.5s
128:	learn: 0.3124997	total: 8.84s	remaining: 25.4s
129:	learn: 0.3124407	total: 8.9s	remaining: 25.3s
130:	learn: 0.3123597	total: 8.97s	remaining: 25.3s
131:	learn: 0.3122951	total: 9.04s	remaining: 25.2s
132:	learn: 0.3122485	total: 9.1s	remaining: 25.1s
133:	learn: 0.3121750	total: 9.16s	remaining: 25s
134:	learn: 0.3121193	total: 9.22s	remaining: 24.9s
135:	learn: 0.3120307	total: 9.29s	remaining: 24.9s
136:	learn: 0.3119922	total: 9.36s	remaining: 24.8s
137:	learn: 0.3119464	total: 9.42s	remaining: 24.7s
138:	learn: 0.3118822	total: 9.48s	remaining: 24.6s
139:	learn: 0.3117960	total: 9.55s	remaining: 24.6s
140:	learn: 0.3117393	total: 9.61s	remaining: 24.5s
141:	learn: 0.3116573	total: 9.68s	remaining: 24.4s
142:	learn: 0.3115956	total: 9.74s	remaining: 24.3s
143:	learn: 0.3115507	total: 9.81s	remaining: 24.2s
144:	learn: 0.3114784	total: 9.87s	remaining: 24.2s
145:	learn: 0.3113948	total: 9.94s	remaining: 24.1s
146:	learn: 0.3113209	total: 10s	remaining: 24s
147:	learn: 0.3112299	total: 10.1s	remaining: 23.9s
148:	learn: 0.3111400	total: 10.1s	remaining: 23.9s
149:	learn: 0.3110998	total: 10.2s	remaining: 23.8s
150:	learn: 0.3110330	total: 10.3s	remaining: 23.7s
151:	learn: 0.3109699	total: 10.3s	remaining: 23.7s
152:	learn: 0.3109067	total: 10.4s	remaining: 23.6s
153:	learn: 0.3108680	total: 10.5s	remaining: 23.5s
154:	learn: 0.3108355	total: 10.5s	remaining: 23.5s
155:	learn: 0.3107998	total: 10.6s	remaining: 23.4s
156:	learn: 0.3107230	total: 10.7s	remaining: 23.3s
157:	learn: 0.3106566	total: 10.7s	remaining: 23.3s
158:	learn: 0.3105895	total: 10.8s	remaining: 23.2s
159:	learn: 0.3105147	total: 10.9s	remaining: 23.1s
160:	learn: 0.3104520	total: 10.9s	remaining: 23s
161:	learn: 0.3104077	total: 11s	remaining: 23s
162:	learn: 0.3103735	total: 11.1s	remaining: 22.9s
163:	learn: 0.3103145	total: 11.1s	remaining: 22.8s
164:	learn: 0.3102795	total: 11.2s	remaining: 22.7s
165:	learn: 0.3102146	total: 11.2s	remaining: 22.6s
166:	learn: 0.3101582	total: 11.3s	remaining: 22.6s
167:	learn: 0.3100947	total: 11.4s	remaining: 22.5s
168:	learn: 0.3100584	total: 11.4s	remaining: 22.4s
169:	learn: 0.3100218	total: 11.5s	remaining: 22.3s
170:	learn: 0.3099885	total: 11.6s	remaining: 22.3s
171:	learn: 0.3099220	total: 11.6s	remaining: 22.2s
172:	learn: 0.3098613	total: 11.7s	remaining: 22.1s
173:	learn: 0.3098117	total: 11.8s	remaining: 22.1s
174:	learn: 0.3097794	total: 11.8s	remaining: 22s
175:	learn: 0.3097435	total: 11.9s	remaining: 21.9s
176:	learn: 0.3096645	total: 12s	remaining: 21.9s
177:	learn: 0.3095979	total: 12.1s	remaining: 21.9s
178:	learn: 0.3095531	total: 12.2s	remaining: 21.8s
179:	learn: 0.3094650	total: 12.2s	remaining: 21.7s
180:	learn: 0.3094006	total: 12.3s	remaining: 21.6s
181:	learn: 0.3093691	total: 12.3s	remaining: 21.6s
182:	learn: 0.3093113	total: 12.4s	remaining: 21.5s
183:	learn: 0.3092372	total: 12.5s	remaining: 21.4s
184:	learn: 0.3091678	total: 12.5s	remaining: 21.3s
185:	learn: 0.3091265	total: 12.6s	remaining: 21.3s
186:	learn: 0.3090660	total: 12.7s	remaining: 21.2s
187:	learn: 0.3089931	total: 12.7s	remaining: 21.1s
188:	learn: 0.3089263	total: 12.8s	remaining: 21.1s
189:	learn: 0.3088616	total: 12.9s	remaining: 21s
190:	learn: 0.3088092	total: 12.9s	remaining: 20.9s
191:	learn: 0.3087666	total: 13s	remaining: 20.8s
192:	learn: 0.3086923	total: 13.1s	remaining: 20.8s
193:	learn: 0.3086139	total: 13.1s	remaining: 20.7s
194:	learn: 0.3085668	total: 13.2s	remaining: 20.6s
195:	learn: 0.3085043	total: 13.3s	remaining: 20.6s
196:	learn: 0.3084282	total: 13.3s	remaining: 20.5s
197:	learn: 0.3083854	total: 13.4s	remaining: 20.4s
198:	learn: 0.3083732	total: 13.5s	remaining: 20.4s
199:	learn: 0.3083143	total: 13.5s	remaining: 20.3s
200:	learn: 0.3082525	total: 13.6s	remaining: 20.3s
201:	learn: 0.3082432	total: 13.7s	remaining: 20.2s
202:	learn: 0.3081731	total: 13.8s	remaining: 20.1s
203:	learn: 0.3081101	total: 13.8s	remaining: 20.1s
204:	learn: 0.3080587	total: 13.9s	remaining: 20s
205:	learn: 0.3080035	total: 14s	remaining: 19.9s
206:	learn: 0.3079451	total: 14s	remaining: 19.9s
207:	learn: 0.3078750	total: 14.1s	remaining: 19.8s
208:	learn: 0.3078290	total: 14.2s	remaining: 19.7s
209:	learn: 0.3077740	total: 14.2s	remaining: 19.6s
210:	learn: 0.3077127	total: 14.3s	remaining: 19.6s
211:	learn: 0.3076685	total: 14.4s	remaining: 19.5s
212:	learn: 0.3076011	total: 14.4s	remaining: 19.5s
213:	learn: 0.3075295	total: 14.5s	remaining: 19.4s
214:	learn: 0.3074716	total: 14.6s	remaining: 19.3s
215:	learn: 0.3074113	total: 14.6s	remaining: 19.3s
216:	learn: 0.3073643	total: 14.7s	remaining: 19.2s
217:	learn: 0.3073212	total: 14.8s	remaining: 19.1s
218:	learn: 0.3072438	total: 14.9s	remaining: 19.1s
219:	learn: 0.3071857	total: 14.9s	remaining: 19s
220:	learn: 0.3071260	total: 15s	remaining: 19s
221:	learn: 0.3070640	total: 15.1s	remaining: 18.9s
222:	learn: 0.3070265	total: 15.2s	remaining: 18.8s
223:	learn: 0.3069607	total: 15.2s	remaining: 18.8s
224:	learn: 0.3068915	total: 15.3s	remaining: 18.7s
225:	learn: 0.3068207	total: 15.3s	remaining: 18.6s
226:	learn: 0.3067525	total: 15.4s	remaining: 18.5s
227:	learn: 0.3067123	total: 15.5s	remaining: 18.4s
228:	learn: 0.3066416	total: 15.5s	remaining: 18.4s
229:	learn: 0.3065984	total: 15.6s	remaining: 18.3s
230:	learn: 0.3065297	total: 15.7s	remaining: 18.2s
231:	learn: 0.3064806	total: 15.7s	remaining: 18.2s
232:	learn: 0.3064524	total: 15.8s	remaining: 18.1s
233:	learn: 0.3064108	total: 15.9s	remaining: 18s
234:	learn: 0.3063560	total: 15.9s	remaining: 18s
235:	learn: 0.3063231	total: 16s	remaining: 17.9s
236:	learn: 0.3062696	total: 16.1s	remaining: 17.8s
237:	learn: 0.3062332	total: 16.1s	remaining: 17.8s
238:	learn: 0.3061831	total: 16.2s	remaining: 17.7s
239:	learn: 0.3061668	total: 16.3s	remaining: 17.6s
240:	learn: 0.3061235	total: 16.3s	remaining: 17.6s
241:	learn: 0.3060752	total: 16.4s	remaining: 17.5s
242:	learn: 0.3060239	total: 16.5s	remaining: 17.4s
243:	learn: 0.3059706	total: 16.6s	remaining: 17.4s
244:	learn: 0.3059305	total: 16.6s	remaining: 17.3s
245:	learn: 0.3058695	total: 16.7s	remaining: 17.2s
246:	learn: 0.3058341	total: 16.8s	remaining: 17.2s
247:	learn: 0.3057629	total: 16.8s	remaining: 17.1s
248:	learn: 0.3057093	total: 16.9s	remaining: 17s
249:	learn: 0.3056809	total: 16.9s	remaining: 16.9s
250:	learn: 0.3056130	total: 17s	remaining: 16.9s
251:	learn: 0.3055672	total: 17.1s	remaining: 16.8s
252:	learn: 0.3055154	total: 17.1s	remaining: 16.7s
253:	learn: 0.3054697	total: 17.2s	remaining: 16.7s
254:	learn: 0.3054316	total: 17.3s	remaining: 16.6s
255:	learn: 0.3053977	total: 17.4s	remaining: 16.5s
256:	learn: 0.3053384	total: 17.4s	remaining: 16.5s
257:	learn: 0.3053194	total: 17.5s	remaining: 16.4s
258:	learn: 0.3052701	total: 17.6s	remaining: 16.3s
259:	learn: 0.3052269	total: 17.6s	remaining: 16.3s
260:	learn: 0.3051650	total: 17.7s	remaining: 16.2s
261:	learn: 0.3051161	total: 17.8s	remaining: 16.1s
262:	learn: 0.3050611	total: 17.8s	remaining: 16.1s
263:	learn: 0.3050096	total: 17.9s	remaining: 16s
264:	learn: 0.3049422	total: 18s	remaining: 15.9s
265:	learn: 0.3048913	total: 18s	remaining: 15.9s
266:	learn: 0.3048536	total: 18.1s	remaining: 15.8s
267:	learn: 0.3047839	total: 18.2s	remaining: 15.7s
268:	learn: 0.3047204	total: 18.2s	remaining: 15.6s
269:	learn: 0.3046605	total: 18.3s	remaining: 15.6s
270:	learn: 0.3046301	total: 18.4s	remaining: 15.5s
271:	learn: 0.3045649	total: 18.4s	remaining: 15.4s
272:	learn: 0.3045422	total: 18.5s	remaining: 15.4s
273:	learn: 0.3045048	total: 18.6s	remaining: 15.3s
274:	learn: 0.3044626	total: 18.6s	remaining: 15.3s
275:	learn: 0.3044135	total: 18.7s	remaining: 15.2s
276:	learn: 0.3044023	total: 18.8s	remaining: 15.1s
277:	learn: 0.3043474	total: 18.8s	remaining: 15s
278:	learn: 0.3042885	total: 18.9s	remaining: 15s
279:	learn: 0.3042627	total: 19s	remaining: 14.9s
280:	learn: 0.3042155	total: 19s	remaining: 14.8s
281:	learn: 0.3041678	total: 19.1s	remaining: 14.8s
282:	learn: 0.3041406	total: 19.2s	remaining: 14.7s
283:	learn: 0.3041039	total: 19.2s	remaining: 14.6s
284:	learn: 0.3040264	total: 19.3s	remaining: 14.6s
285:	learn: 0.3039660	total: 19.4s	remaining: 14.5s
286:	learn: 0.3038894	total: 19.4s	remaining: 14.4s
287:	learn: 0.3038459	total: 19.5s	remaining: 14.3s
288:	learn: 0.3037768	total: 19.6s	remaining: 14.3s
289:	learn: 0.3037345	total: 19.6s	remaining: 14.2s
290:	learn: 0.3036828	total: 19.7s	remaining: 14.1s
291:	learn: 0.3036222	total: 19.7s	remaining: 14.1s
292:	learn: 0.3035685	total: 19.8s	remaining: 14s
293:	learn: 0.3035120	total: 19.9s	remaining: 13.9s
294:	learn: 0.3034612	total: 19.9s	remaining: 13.9s
295:	learn: 0.3034217	total: 20s	remaining: 13.8s
296:	learn: 0.3033656	total: 20.1s	remaining: 13.7s
297:	learn: 0.3033297	total: 20.1s	remaining: 13.7s
298:	learn: 0.3032800	total: 20.2s	remaining: 13.6s
299:	learn: 0.3032284	total: 20.3s	remaining: 13.5s
300:	learn: 0.3031807	total: 20.3s	remaining: 13.4s
301:	learn: 0.3031326	total: 20.4s	remaining: 13.4s
302:	learn: 0.3031264	total: 20.5s	remaining: 13.3s
303:	learn: 0.3030864	total: 20.5s	remaining: 13.2s
304:	learn: 0.3030456	total: 20.6s	remaining: 13.2s
305:	learn: 0.3029996	total: 20.7s	remaining: 13.1s
306:	learn: 0.3029838	total: 20.7s	remaining: 13s
307:	learn: 0.3029649	total: 20.8s	remaining: 13s
308:	learn: 0.3029121	total: 20.9s	remaining: 12.9s
309:	learn: 0.3028451	total: 21s	remaining: 12.8s
310:	learn: 0.3028085	total: 21s	remaining: 12.8s
311:	learn: 0.3027462	total: 21.1s	remaining: 12.7s
312:	learn: 0.3026957	total: 21.2s	remaining: 12.7s
313:	learn: 0.3026425	total: 21.2s	remaining: 12.6s
314:	learn: 0.3025936	total: 21.3s	remaining: 12.5s
315:	learn: 0.3025417	total: 21.4s	remaining: 12.5s
316:	learn: 0.3024863	total: 21.5s	remaining: 12.4s
317:	learn: 0.3024513	total: 21.5s	remaining: 12.3s
318:	learn: 0.3024006	total: 21.6s	remaining: 12.3s
319:	learn: 0.3023638	total: 21.7s	remaining: 12.2s
320:	learn: 0.3023145	total: 21.7s	remaining: 12.1s
321:	learn: 0.3022627	total: 21.8s	remaining: 12.1s
322:	learn: 0.3022184	total: 21.9s	remaining: 12s
323:	learn: 0.3021858	total: 21.9s	remaining: 11.9s
324:	learn: 0.3021117	total: 22s	remaining: 11.9s
325:	learn: 0.3020774	total: 22.1s	remaining: 11.8s
326:	learn: 0.3020164	total: 22.2s	remaining: 11.7s
327:	learn: 0.3019905	total: 22.2s	remaining: 11.7s
328:	learn: 0.3019549	total: 22.3s	remaining: 11.6s
329:	learn: 0.3019013	total: 22.4s	remaining: 11.5s
330:	learn: 0.3018520	total: 22.5s	remaining: 11.5s
331:	learn: 0.3018416	total: 22.5s	remaining: 11.4s
332:	learn: 0.3018176	total: 22.6s	remaining: 11.3s
333:	learn: 0.3017559	total: 22.7s	remaining: 11.3s
334:	learn: 0.3017067	total: 22.7s	remaining: 11.2s
335:	learn: 0.3016577	total: 22.8s	remaining: 11.1s
336:	learn: 0.3016366	total: 22.9s	remaining: 11.1s
337:	learn: 0.3015909	total: 22.9s	remaining: 11s
338:	learn: 0.3015789	total: 23s	remaining: 10.9s
339:	learn: 0.3015196	total: 23s	remaining: 10.8s
340:	learn: 0.3014674	total: 23.1s	remaining: 10.8s
341:	learn: 0.3014340	total: 23.2s	remaining: 10.7s
342:	learn: 0.3013787	total: 23.3s	remaining: 10.6s
343:	learn: 0.3013266	total: 23.3s	remaining: 10.6s
344:	learn: 0.3012543	total: 23.4s	remaining: 10.5s
345:	learn: 0.3012042	total: 23.5s	remaining: 10.4s
346:	learn: 0.3011374	total: 23.5s	remaining: 10.4s
347:	learn: 0.3010811	total: 23.6s	remaining: 10.3s
348:	learn: 0.3010377	total: 23.6s	remaining: 10.2s
349:	learn: 0.3009687	total: 23.7s	remaining: 10.2s
350:	learn: 0.3009079	total: 23.8s	remaining: 10.1s
351:	learn: 0.3008832	total: 23.8s	remaining: 10s
352:	learn: 0.3008400	total: 23.9s	remaining: 9.96s
353:	learn: 0.3008219	total: 24s	remaining: 9.89s
354:	learn: 0.3008001	total: 24s	remaining: 9.82s
355:	learn: 0.3007581	total: 24.1s	remaining: 9.75s
356:	learn: 0.3007131	total: 24.2s	remaining: 9.68s
357:	learn: 0.3006952	total: 24.2s	remaining: 9.61s
358:	learn: 0.3006396	total: 24.3s	remaining: 9.54s
359:	learn: 0.3005936	total: 24.4s	remaining: 9.48s
360:	learn: 0.3005228	total: 24.4s	remaining: 9.41s
361:	learn: 0.3004567	total: 24.5s	remaining: 9.34s
362:	learn: 0.3003945	total: 24.6s	remaining: 9.28s
363:	learn: 0.3003604	total: 24.6s	remaining: 9.21s
364:	learn: 0.3003098	total: 24.7s	remaining: 9.14s
365:	learn: 0.3002789	total: 24.8s	remaining: 9.07s
366:	learn: 0.3002180	total: 24.9s	remaining: 9.01s
367:	learn: 0.3001644	total: 24.9s	remaining: 8.94s
368:	learn: 0.3001441	total: 25.1s	remaining: 8.91s
369:	learn: 0.3000956	total: 25.2s	remaining: 8.84s
370:	learn: 0.3000715	total: 25.2s	remaining: 8.77s
371:	learn: 0.3000266	total: 25.3s	remaining: 8.71s
372:	learn: 0.2999783	total: 25.4s	remaining: 8.64s
373:	learn: 0.2999212	total: 25.5s	remaining: 8.59s
374:	learn: 0.2998668	total: 25.6s	remaining: 8.53s
375:	learn: 0.2998239	total: 25.7s	remaining: 8.47s
376:	learn: 0.2997813	total: 25.8s	remaining: 8.4s
377:	learn: 0.2997366	total: 25.8s	remaining: 8.34s
378:	learn: 0.2996989	total: 25.9s	remaining: 8.27s
379:	learn: 0.2996470	total: 26s	remaining: 8.21s
380:	learn: 0.2995974	total: 26.1s	remaining: 8.14s
381:	learn: 0.2995634	total: 26.1s	remaining: 8.07s
382:	learn: 0.2995013	total: 26.2s	remaining: 8.01s
383:	learn: 0.2994533	total: 26.3s	remaining: 7.94s
384:	learn: 0.2994061	total: 26.3s	remaining: 7.87s
385:	learn: 0.2993654	total: 26.4s	remaining: 7.8s
386:	learn: 0.2993290	total: 26.5s	remaining: 7.73s
387:	learn: 0.2992694	total: 26.6s	remaining: 7.67s

In [4]:
oof_preds = np.zeros(len(X_train))
fold_auc_scores = []

for fold, (train_idx, val_idx) in enumerate(skf.split(X_train, y_train)):
    X_tr, X_val = X_train.iloc[train_idx], X_train.iloc[val_idx]
    y_tr, y_val = y_train.iloc[train_idx], y_train.iloc[val_idx]

    model_kf = CatBoostClassifier(
        iterations=500,
        eval_metric='AUC',
        cat_features=cat_features,
        random_state = 42,
        verbose=0
    )

    model_kf.fit(
        X_tr, y_tr,
        eval_set = (X_val, y_val),
        early_stopping_rounds=50,
        use_best_model = True,
    )

    val_pred = model_kf.predict_proba(X_val)[:, 1]
    oof_preds[val_idx] = val_pred

    fold_auc = roc_auc_score(y_val, val_pred)
    fold_auc_scores.append(fold_auc)
    print(f"Fold {fold+1}: ROC-AUC = {fold_auc:.4f}")

print("Finish:")
print(f"Mean ROC-AUC: {np.mean(fold_auc_scores):.4f}")
print(f"OOF ROC-AUC: {roc_auc_score(y_train, oof_preds)}")

Fold 1: ROC-AUC = 0.8897
Fold 2: ROC-AUC = 0.8892
Fold 3: ROC-AUC = 0.8908
Fold 4: ROC-AUC = 0.8910
Fold 5: ROC-AUC = 0.8872
Finish:
Mean ROC-AUC: 0.8896
OOF ROC-AUC: 0.8895660376227704

In [5]:
from sklearn.preprocessing import OneHotEncoder
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier

encoder = OneHotEncoder()

X_train_encoded = pd.get_dummies(X_train, columns=cat_features, drop_first=True, dtype=int)
X_test_encoded = pd.get_dummies(X_test, columns=cat_features, drop_first=True, dtype=int)

oof_preds_xgb = np.zeros(len(X_train))
oof_preds_lgbm = np.zeros(len(X_train))

fold_auc_scores_xgb = []
fold_auc_scores_lgbm = []


for fold, (train_idx, val_idx) in enumerate(skf.split(X_train_encoded, y_train)):
    X_tr, X_val = X_train_encoded.iloc[train_idx], X_train_encoded.iloc[val_idx]
    y_tr, y_val = y_train.iloc[train_idx], y_train.iloc[val_idx]

    xgb = XGBClassifier(
        n_estimators=500,
        random_state=42 
    )

    lgbm = LGBMClassifier(
        n_estimators=500,
        random_state=42,
        verbose=-1
    )

    xgb.fit(X_tr, y_tr)
    lgbm.fit(X_tr, y_tr)

    val_pred_xgb = xgb.predict_proba(X_val)[:, 1]
    val_pred_lgbm = lgbm.predict_proba(X_val)[:, 1]

    oof_preds_xgb[val_idx] = val_pred_xgb
    oof_preds_lgbm[val_idx] = val_pred_lgbm

    fold_auc_xgb = roc_auc_score(y_val, val_pred_xgb)
    fold_auc_lgbm = roc_auc_score(y_val, val_pred_lgbm)

    fold_auc_scores_xgb.append(fold_auc_xgb)
    fold_auc_scores_lgbm.append(fold_auc_lgbm)

    print(f"Fold: {fold+1}")
    print(f"XGBoost: {fold_auc_xgb:.4f}")
    print(f"LGBM: {fold_auc_lgbm:.4f}")
print("XGBoost:")
print(f"Mean ROC-AUC: {np.mean(fold_auc_scores_xgb):.4f}")
print(f"OOF ROC-AUC: {roc_auc_score(y_train, oof_preds_xgb)}")

print("LGBM:")
print(f"Mean ROC-AUC: {np.mean(fold_auc_scores_lgbm):.4f}")
print(f"OOF ROC-AUC: {roc_auc_score(y_train, oof_preds_lgbm)}")
    
print("CatBoost")
print(f"Mean ROC-AUC: {np.mean(fold_auc_scores):.4f}")
print(f"OOF ROC-AUC: {roc_auc_score(y_train, oof_preds)}")

Fold: 1
XGBoost: 0.8747
LGBM: 0.8880
Fold: 2
XGBoost: 0.8746
LGBM: 0.8874
Fold: 3
XGBoost: 0.8766
LGBM: 0.8895
Fold: 4
XGBoost: 0.8759
LGBM: 0.8896
Fold: 5
XGBoost: 0.8723
LGBM: 0.8844
XGBoost:
Mean ROC-AUC: 0.8748
OOF ROC-AUC: 0.8747907474345168
LGBM:
Mean ROC-AUC: 0.8878
OOF ROC-AUC: 0.8877548926670592
CatBoost
Mean ROC-AUC: 0.8896
OOF ROC-AUC: 0.8895660376227704

In [6]:
# feature engenering

# 1. financial features
X_train['Balance_per_Product'] = X_train['Balance'] / (X_train['NumOfProducts']+0.00001)
X_test['Balance_per_Product'] = X_test['Balance'] / (X_test['NumOfProducts']+0.00001)

X_train['Balance_per_Salary'] = X_train['Balance'] / (X_train['EstimatedSalary']+0.00001)
X_test['Balance_per_Salary'] = X_test['Balance'] / (X_test['EstimatedSalary']+0.00001)

X_train['CreditScore_per_Age'] = X_train['CreditScore'] / (X_train['Age']+0.00001)
X_test['CreditScore_per_Age'] = X_test['CreditScore'] / (X_test['Age']+0.00001)

# 2. behavioral features
X_train['IsActiveMember_HasCrCard'] = X_train['IsActiveMember'] * X_train['HasCrCard']
X_test['IsActiveMember_HasCrCard'] = X_test['IsActiveMember'] * X_test['HasCrCard']

X_train['Age_Group'] = X_train['Age'] // 10
X_test['Age_Group'] = X_test['Age'] // 10

X_train.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Balance_per_Product,Balance_per_Salary,CreditScore_per_Age,IsActiveMember_HasCrCard,Age_Group
0,668,France,Male,33.0,3,0.00,2,1.0,0.0,181449.97,0.000000,0.000000,20.242418,0.0,3.0
1,627,France,Male,33.0,1,0.00,2,1.0,1.0,49503.50,0.000000,0.000000,18.999994,1.0,3.0
2,678,France,Male,40.0,10,0.00,2,1.0,0.0,184866.69,0.000000,0.000000,16.949996,0.0,4.0
3,581,France,Male,34.0,2,148882.54,1,1.0,1.0,84560.88,148881.051189,1.760655,17.088230,1.0,3.0
4,716,Spain,Male,33.0,5,0.00,2,1.0,1.0,15068.83,0.000000,0.000000,21.696963,1.0,3.0

In [7]:
# Data preparation for LGBM
X_train_freq = X_train.copy()
X_test_freq = X_test.copy()

X_train_freq['Geography_freq'] = X_train_freq['Geography'].map(X_train_freq['Geography'].value_counts())
X_train_freq['Gender_freq'] = X_train_freq['Gender'].map(X_train_freq['Gender'].value_counts())

X_test_freq['Geography_freq'] = X_test_freq['Geography'].map(X_train_freq['Geography'].value_counts())
X_test_freq['Gender_freq'] = X_test_freq['Gender'].map(X_train_freq['Gender'].value_counts())

X_train_freq=X_train_freq.drop(columns=cat_features)
X_test_freq=X_test_freq.drop(columns=cat_features)

X_train_freq.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Balance_per_Product,Balance_per_Salary,CreditScore_per_Age,IsActiveMember_HasCrCard,Age_Group,Geography_freq,Gender_freq
0,668,33.0,3,0.00,2,1.0,0.0,181449.97,0.000000,0.000000,20.242418,0.0,3.0,94215,93150
1,627,33.0,1,0.00,2,1.0,1.0,49503.50,0.000000,0.000000,18.999994,1.0,3.0,94215,93150
2,678,40.0,10,0.00,2,1.0,0.0,184866.69,0.000000,0.000000,16.949996,0.0,4.0,94215,93150
3,581,34.0,2,148882.54,1,1.0,1.0,84560.88,148881.051189,1.760655,17.088230,1.0,3.0,94215,93150
4,716,33.0,5,0.00,2,1.0,1.0,15068.83,0.000000,0.000000,21.696963,1.0,3.0,36213,93150

In [8]:
from catboost import CatBoostClassifier
from lightgbm import LGBMClassifier
from sklearn.metrics import roc_auc_score

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

oof_cb = np.zeros(len(X_train))
oof_lgbm = np.zeros(len(X_train))

fold_auc_scores_cb = []
fold_auc_scores_lgbm = []

for fold, (train_idx, val_idx) in enumerate(skf.split(X_train, y_train)):

    X_tr_cb, X_val_cb = X_train.iloc[train_idx], X_train.iloc[val_idx]
    X_tr_lgbm, X_val_lgbm = X_train_freq.iloc[train_idx], X_train_freq.iloc[val_idx]
    y_tr, y_val = y_train.iloc[train_idx], y_train.iloc[val_idx]

    cb = CatBoostClassifier(
        iterations=500,
        cat_features=cat_features,
        early_stopping_rounds=50,
        random_state=42,
        verbose=0
    )

    lgbm = LGBMClassifier(
        n_estimators=500,
        early_stopping_rounds=50,
        learning_rate=0.04,
        random_state=42,
        verbose=-1
    )

    cb.fit(X_tr_cb, y_tr,
           eval_set=(X_val_cb, y_val)
           )
    lgbm.fit(X_tr_lgbm, y_tr,
             eval_set=[(X_val_lgbm, y_val)]
            )

    val_pred_cb = cb.predict_proba(X_val_cb)[:, 1]
    val_pred_lgbm = lgbm.predict_proba(X_val_lgbm)[:, 1]

    oof_cb[val_idx] = val_pred_cb
    oof_lgbm[val_idx] = val_pred_lgbm

    fold_auc_cb = roc_auc_score(y_val, val_pred_cb)
    fold_auc_lgbm = roc_auc_score(y_val, val_pred_lgbm)

    fold_auc_scores_cb.append(fold_auc_cb)
    fold_auc_scores_lgbm.append(fold_auc_lgbm)

    print(f"Fold: {fold+1}")
    print(f"CatBoost: {fold_auc_cb:.4f}")
    print(f"LightGBM: {fold_auc_lgbm:.4f}")

print('Fit finished:')
print("CatBoost")
print(f"Mean ROC-AUC: {np.mean(fold_auc_scores_cb):.4f}")
print(f"OOF ROC-AUC: {roc_auc_score(y_train, oof_cb):.4f}")

print("LightGBM")
print(f"Mean ROC-AUC: {np.mean(fold_auc_scores_lgbm):.4f}")
print(f"OOF ROC-AUC: {roc_auc_score(y_train, oof_lgbm):.4f}")

c:\Users\IVAN\AppData\Local\Programs\Python\Python311\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

Fold: 1
CatBoost: 0.8896
LightGBM: 0.8899

c:\Users\IVAN\AppData\Local\Programs\Python\Python311\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

Fold: 2
CatBoost: 0.8894
LightGBM: 0.8894

c:\Users\IVAN\AppData\Local\Programs\Python\Python311\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

Fold: 3
CatBoost: 0.8905
LightGBM: 0.8910

c:\Users\IVAN\AppData\Local\Programs\Python\Python311\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

Fold: 4
CatBoost: 0.8911
LightGBM: 0.8907

c:\Users\IVAN\AppData\Local\Programs\Python\Python311\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)

Fold: 5
CatBoost: 0.8872
LightGBM: 0.8867
Fit finished:
CatBoost
Mean ROC-AUC: 0.8895
OOF ROC-AUC: 0.8895
LightGBM
Mean ROC-AUC: 0.8895
OOF ROC-AUC: 0.8895

In [9]:
best_w = 0.5
best_auc = 0.5
for w in np.linspace(0, 1, 101):
    blend_oof = w * oof_cb + (1-w) * oof_lgbm
    score = roc_auc_score(y_train, blend_oof)

    if score > best_auc:
        best_auc = score
        best_w = w

print(f"Оптимальный вес CatBoost: {best_w:.2f}")
print(f"Оптимальный вес LightGBM: {1 - best_w:.2f}")
print(f"OOF ROC-AUC Catboost: {roc_auc_score(y_train, oof_cb):.5f}")
print(f"OOF ROC-AUC LightGBM: {roc_auc_score(y_train, oof_lgbm):.5f}")
print(f"OOF ROC-AUC Blending: {best_auc:.5f}")

Оптимальный вес CatBoost: 0.50
Оптимальный вес LightGBM: 0.50
OOF ROC-AUC Catboost: 0.88953
OOF ROC-AUC LightGBM: 0.88953
OOF ROC-AUC Blending: 0.88993

In [13]:
test_preds_cb = np.zeros(len(X_test))
test_preds_lgbm = np.zeros(len(X_test_freq))

for fold, (train_idx, val_idx) in enumerate(skf.split(X_train, y_train)):

    X_tr_cb, X_val_cb = X_train.iloc[train_idx], X_train.iloc[val_idx]
    X_tr_lgbm, X_val_lgbm = X_train_freq.iloc[train_idx], X_train_freq.iloc[val_idx]
    y_tr, y_val = y_train.iloc[train_idx], y_train.iloc[val_idx]

    cb = CatBoostClassifier(
        iterations=500,
        cat_features=cat_features,
        early_stopping_rounds=50,
        random_state=42,
        verbose=0
    )

    lgbm = LGBMClassifier(
        n_estimators=500,
        early_stopping_rounds=50,
        learning_rate=0.04,
        random_state=42,
        verbose=-1
    )

    cb.fit(X_tr_cb, y_tr,
           eval_set=(X_val_cb, y_val)
           )
    lgbm.fit(X_tr_lgbm, y_tr,
             eval_set=[(X_val_lgbm, y_val)]
            )
    test_preds_cb += cb.predict_proba(X_test)[:, 1] / skf.n_splits
    test_preds_lgbm += lgbm.predict_proba(X_test_freq)[:, 1] / skf.n_splits

final_test_preds = best_w * test_preds_cb + (1-best_w) * test_preds_lgbm

sub = pd.read_csv(r"C:\Users\IVAN\Desktop\Machine-Learning-Roadmap-Theory-and-Practice\Files\Binary Classification with a Bank Churn Dataset\sample_submission.csv")

sub['Exited'] = final_test_preds
sub.to_csv('submission_blend.csv', index=False)

c:\Users\IVAN\AppData\Local\Programs\Python\Python311\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
c:\Users\IVAN\AppData\Local\Programs\Python\Python311\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
c:\Users\IVAN\AppData\Local\Programs\Python\Python311\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
c:\Users\IVAN\AppData\Local\Programs\Python\Python311\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)
c:\Users\IVAN\AppData\Local\Programs\Python\Python311\Lib\site-packages\lightgbm\sklearn.py:1106: LGBMDeprecationWarning: The argument 'eval_set' is deprecated, use 'eval_X' and 'eval_y' instead.
  eval_set = _validate_eval_set_Xy(eval_set=eval_set, eval_X=eval_X, eval_y=eval_y)